### ISSUE TITLE
tlt and defocus files do not correspond to the tilt series

### ISSUE THREAD

**Issue by Vilax** [scipion-em/scipion-em-novactf#42]
I got this error:
![imagen](https://user-images.githubusercontent.com/12271438/223503428-63995414-0bb9-493a-aa09-c73d3a153e86.png)

The reason seems to be a non matching between the tlt file and the tilt series. Similarly with the defocus file (see that the _11 inthe filename points that the ts 11 is processed).

![imagen](https://user-images.githubusercontent.com/12271438/223503861-17555711-2fe7-44e7-9066-c16eabbb9f88.png)

The hypothesis is confirmed when the angles of the ts 11 are checked:

![imagen](https://user-images.githubusercontent.com/12271438/223504154-034d834d-07df-4143-80b5-a4d620cbaec1.png)

**Comment by azazellochg** [comment]
@Vilax Please attach both complete log files

**Comment by Vilax** [comment]
@azazellochg I removed that project, but I created a new one and I can get an error. Probably related with the old one. In this case the error is in the convert, but I think the error is related with the name or id identification

Here is the Error:

In the convertInputStep

0001:   Couldn't run the code in a thread.
00002:   Traceback (most recent call last):
00003:     File "/home/vilas/opt/miniconda/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/executor.py", line 148, in run
00004:       self.step._run()  # not self.step.run() , to avoid race conditions
00005:     File "/home/vilas/opt/miniconda/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 252, in _run
00006:       resultFiles = self._runFunc()
00007:     File "/home/vilas/opt/miniconda/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 248, in _runFunc
00008:       return self._func(*self._args)
00009:     File "/home/vilas/opt/scipion/plugins/scipion-em-novactf/novactf/protocols/protocol_tomoDefocus.py", line 157, in convertInputStep
00010:       ts.generateTltFile(angleFilePath)
00011:     File "/home/vilas/opt/scipion/plugins/scipion-em-tomo/tomo/objects.py", line 330, in generateTltFile
00012:       with open(tltFilePath, 'w') as f:
00013:   FileNotFoundError: [Errno 2] No such file or directory: 'tomo2/Runs/001506_ProtNovaCtfTomoDefocus/tmp/tomo2.tlt'
00014:   Protocol failed: [Errno 2] No such file or directory: 'tomo2/Runs/001506_ProtNovaCtfTomoDefocus/tmp/tomo2.tlt'

**Comment by azazellochg** [comment]
1) 0001: Couldn't run the code in a thread. - your scipion python or your PC has a problem. Please try to reproduce this error on a different pc.
2) since you still have not attached both log files
```
00009: File "/home/vilas/opt/scipion/plugins/scipion-em-novactf/novactf/protocols/protocol_tomoDefocus.py", line 157, in convertInputStep
00010: ts.generateTltFile(angleFilePath)
```
you are not using devel code

**Comment by azazellochg** [comment]
ALso, tomo2/Runs/001506_ProtNovaCtfTomoDefocus/tmp/tomo2.tlt is a strange path, the commands are run from the project folder so it should start from "Runs/"

**Comment by pconesa** [comment]
@Vilax any clear way to reproduce this?

**Comment by Vilax** [comment]
I think it is reproducible with empiar 10453. I have a project, I will send it get a log. I can try to find the proejct

**Comment by azazellochg** [comment]
Has to be something with file names then. Thanks for the pointer, I might
have a look this weekend

**Comment by azazellochg** [comment]
I could not reproduce it so far with TS_005 and TS_007 from EMPIAR-10453:
![image](https://github.com/scipion-em/scipion-em-novactf/assets/6952870/417ffe3b-7db2-493e-a0a7-b35b3b858ce6)
However, the ctf estimation on these TS is very problematic, I had to do it manually with imod - none of the other methods worked.

Can you verify your ctf estimation with cistem? Maybe it has failed for some tilts?

**Comment by azazellochg** [comment]
Nevermind, I found optimal parameter for ctffind to work, and novactf compute defocus still works
