### ISSUE TITLE
3d CTF - Erase gold beads yes error

### ISSUE THREAD

**Issue by wlugmayr** [scipion-em/scipion-em-novactf#51]
In Scipion 3.3.1 stable plugin installation I get the error below if the checkbox above is ticked. The source code has a TODO fixme anyway ;-)

00001:   Couldn't run the code in a thread.
00002:   Traceback (most recent call last):
00003:     File "/gpfs/cssb/software/rhel9/x86_64/scipion/3.x/miniconda/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/executor.py", line 153, in run
00004:       self.step._run()  # not self.step.run() , to avoid race conditions
00005:     File "/gpfs/cssb/software/rhel9/x86_64/scipion/3.x/miniconda/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 254, in _run
00006:       resultFiles = self._runFunc()
00007:     File "/gpfs/cssb/software/rhel9/x86_64/scipion/3.x/miniconda/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 250, in _runFunc
00008:       return self._func(*self._args)
00009:     File "/gpfs/cssb/software/rhel9/x86_64/scipion/3.x/miniconda/envs/scipion3/lib/python3.8/site-packages/novactf/protocols/protocol_tomoReconstruction.py", line 264, in processIntermediateStacksStep
00010:       f'-XformsToApply {outputTmFileName}'
00011:   NameError: name 'outputTmFileName' is not defined

**Comment by pconesa** [comment]
Thanks! There is a review of this plugin here: https://github.com/scipion-em/scipion-em-novactf/pull/50/files

But I don't think it has address this issue. Maybe @Vilax knows.

**Comment by wlugmayr** [comment]
Thanks, I do not need this feature. I just test my new Scipion installation and found this functionality in the advanced section. I clicked it just to see the results and have a quick look and compare the result with the ml eraser fidder from teamtomo. I just wanted to notify you, that there is an error message which could confuse users. Cheers Wolfgang

**Comment by azazellochg** [comment]
erase gold options are now removed/hidden in #50
